# Generated by Django 3.2.4 on 2022-04-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='TaskList',
        ),
    ]
