# Generated by Django 3.2.4 on 2022-04-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
    ]
